<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-B9GSMIV" name="com.testcases.TestCases" tests="19" failures="1" timestamp="2020-09-11T09:47:21 CST" time="111.471" errors="0">
  <testcase name="VerifySuccesfulLogin" time="11.017" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="VerifyUsernameIsInvalid" time="3.766" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="VerifyPasswordIsInvalid" time="3.706" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="Checkboxverification" time="1.331" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="ContextClickandPopUp" time="1.351" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="DragAndDropValidation" time="5.930" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="DropdownValidation" time="1.819" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="DynamicContentValidation" time="14.780" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="DynamicControlsValidation" time="14.184" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="DynamicLoadingValidation" time="7.510" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="FileDownloadValidation" time="8.026" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="FileUploadValidation" time="9.108" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="FloatingMenuValidation" time="3.335" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="IFrameValidation" time="7.481" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="MouseHoverValidation" time="8.506" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="JavaScriptAlertsValidation" time="1.582" classname="com.testcases.TestCases">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	You successfuly clicked an alert - result message mismatch expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
You successfuly clicked an alert - result message mismatch expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.testcases.TestCases.JavaScriptAlertsValidation(TestCases.java:375)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
    </failure>
  </testcase> <!-- JavaScriptAlertsValidation -->
  <system-out/>
  <testcase name="JavaScriptErrorValidation" time="1.125" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="NewTabValidation" time="3.442" classname="com.testcases.TestCases"/>
  <system-out/>
  <testcase name="NotificationMessageValidation" time="3.472" classname="com.testcases.TestCases"/>
  <system-out/>
</testsuite> <!-- com.testcases.TestCases -->
